// Sanity-checks every map in src/levels.ts before it ever reaches a browser. The map checks
// (chunk shape, legend, rails, bug patrols, reachability) live in src/validate.ts, shared with
// the level editor; on top of those, whether a level's id and name can go on a dare card.
//
// Run: npm run levels            (add --map to print the maps with a column ruler)
// Needs Node 22.18+ / 24 — the level data is imported straight from TypeScript.

import { readFileSync, writeFileSync } from "node:fs";
import { LEVELS } from "../src/levels.ts";
import { CHUNK_W, validateLevel } from "../src/validate.ts";
import { missingGlyphs } from "./art.mjs";

let failed = false;
const wantMaps = process.argv.includes("--map");

function checkLevel(level, index) {
  const report = validateLevel(level.chunks);
  const { map, cols, rows, coins, bugs, rails, reach, warnings } = report;
  const errors = [...report.errors];

  // the id and name end up in dare links and on their preview card (api/dare.js)
  if (!/^[a-z0-9-]+$/.test(level.id)) errors.push({ msg: `id "${level.id}" must be lowercase letters, digits and dashes — it goes in a link` });
  const missing = missingGlyphs(`${index + 1}. ${level.name}`);
  if (missing.length) errors.push({ msg: `the dare card font has no ${missing.map((ch) => `"${ch}"`).join(", ")} for the name` });

  const head = `${String(index + 1).padStart(2)}. ${level.name.padEnd(12)} ${String(level.theme).padEnd(7)}` +
    ` ${cols}x${rows}  coins ${String(coins.length).padStart(2)}  bugs ${String(bugs.length).padStart(2)}` +
    `  rails ${rails.length}  reach ${reach.size}`;
  console.log(head);
  for (const w of warnings) console.log(`      warn  ${w.msg}`);
  for (const e of errors) console.log(`      ERROR ${e.msg}`);
  if (errors.length) failed = true;

  if (wantMaps) {
    for (let i = 0; i < level.chunks.length; i++) {
      const from = i * CHUNK_W;
      console.log(`      chunk ${i}  cols ${from}-${from + CHUNK_W - 1}`);
      console.log(`         ${"0    5    10   15   ".slice(0, CHUNK_W)}`);
      map.forEach((row, r) => console.log(`      ${String(r).padStart(2)} ${row.slice(from, from + CHUNK_W)}`));
    }
    for (const b of bugs) console.log(`      bug ${b.at[0]},${b.at[1]} patrols cols ${b.min}-${b.max}`);
    for (const rail of rails) {
      console.log(rail.axis === "x"
        ? `      rail - row ${rail.line}, cols ${rail.from}-${rail.to}`
        : `      rail | col ${rail.line}, rows ${rail.from}-${rail.to}`);
    }
  }
}

console.log(`checking ${LEVELS.length} levels:`);
const ids = new Set();
for (const [i, level] of LEVELS.entries()) {
  if (ids.has(level.id)) {
    console.log(`   ERROR duplicate level id "${level.id}"`);
    failed = true;
  }
  ids.add(level.id);
  checkLevel(level, i);
}

// api/dare.js can't import TypeScript (the Vercel bundler compiles it with the game's tsconfig and fails),
// so it gets the few fields it needs as plain JS. Kept fresh here; a stale copy fails CI and deploys.
const INDEX_FILE = new URL("../api/_levels.js", import.meta.url);
const index =
  "// Generated by scripts/check-levels.mjs from src/levels.ts — run `npm run levels` after changing a level.\n" +
  `export const LEVELS = ${JSON.stringify(LEVELS.map(({ id, name, theme }) => ({ id, name, theme })), null, 2)};\n`;
let current = "";
try {
  current = readFileSync(INDEX_FILE, "utf8");
} catch {}
if (current !== index) {
  if (process.env.CI) {
    console.log("   ERROR api/_levels.js is out of date — run `npm run levels` and commit it");
    failed = true;
  } else {
    writeFileSync(INDEX_FILE, index);
    console.log("updated api/_levels.js");
  }
}

if (failed) {
  console.error("\nlevel check failed");
  process.exit(1);
}
console.log("all good");
