// Generated by scripts/check-levels.mjs from src/levels.ts — run `npm run levels` after changing a level.
export const LEVELS = [
  {
    "id": "first-steps",
    "name": "FIRST STEPS",
    "theme": "meadow"
  },
  {
    "id": "hop-scotch",
    "name": "HOP SCOTCH",
    "theme": "meadow"
  },
  {
    "id": "bug-brigade",
    "name": "BUG BRIGADE",
    "theme": "meadow"
  },
  {
    "id": "dune-runner",
    "name": "DUNE RUNNER",
    "theme": "desert"
  },
  {
    "id": "sandstorm",
    "name": "SANDSTORM",
    "theme": "desert"
  },
  {
    "id": "deep-down",
    "name": "DEEP DOWN",
    "theme": "cavern"
  },
  {
    "id": "drip-trap",
    "name": "DRIP TRAP",
    "theme": "cavern"
  },
  {
    "id": "cold-snap",
    "name": "COLD SNAP",
    "theme": "frost"
  },
  {
    "id": "glacier-gap",
    "name": "GLACIER GAP",
    "theme": "frost"
  },
  {
    "id": "ember-path",
    "name": "EMBER PATH",
    "theme": "magma"
  },
  {
    "id": "the-forge",
    "name": "THE FORGE",
    "theme": "magma"
  }
];
